# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='datecreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='description',
            field=models.TextField(default='Random group', null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='image',
            field=models.ImageField(null=True, upload_to='hood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Tell us something'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='hoods.Hood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hoodwatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hoods.Hood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoods.Profile'),
        ),
    ]
